python.md
the rise slideshow package has been dropped from the Jupyter session (in order to focus better on the essentials, i.e. the notebook).
=> remove rise installation

bash.md, make.md
I don't use windows much, but I tested on an Aalto computer and found these two things to fix.
- I assume nano is preferable to vi.  If not, this should be changed back.
- mingw seems to fail with a download error.  Is it install able for others?
=> Two windows-based installation instruction updates

python.md
i'm planning to test a short introduction to the common workflow language, so i added an optional installation of cwltool (a reference implementation of CWL good for testing and learning)
=> add install instructions for cwltool

python.md
scipy, cython and numba are not used anymore in jupyter lesson, and they're not used anywhere else afaik
=> rm install of unused packages

index.md
Makes sense i think to list required accounts to reduce the time it takes during workshop.
Included accounts: github, travis ci, coveralls, read the docs
=> add list of required accounts, fixes #55

jupyter.md, python.md, snakemake.md
the interleaving of python/jupyter/snakemake with the separate linux/mac and windows installation instructions is confusing
=> split out jupyter and snakemake from python section for less confusion, fixes #63

jupyter.md
I found that, even if installing ipywidgets through conda, I had to
run the setup commands to enable the extensions (unlike for notebook).
After thinking about it, it makes sense to me.
I also reordered it so that jupyterlab instructions are first (it also
makes it more clear that these need to always be done), and also since
we now teach with jupyterlab.
To enable the jupyterlab extensions, I had to `conda install nodejs`.
Is this also expected?
Does anyone know is the above is the expected behavior?  Please don't
merge this until someone confirms.
=> JupyterLab extensions always need activation, even if using conda

jupyter.md
recommend the jupyterlab extension manager rather than install and activate commands in terminal. The extension manager seems to work really well.
Also remove explicit mention of R, octave and julia, and instead link to list of kernels
=> update jupyter installation instructions

git.md, index.md
- I don't think we can make this too obvious - or can we?  Does it
de-emphasize the other verifications?
- Please review: these links will work, right?
=> Add more direct warnings to configure and verify git

editors.md
The original link to the Nano text editor is broken.
This commits replaces the broken link with a functional one.
=> Fix broken link to Nano text editor tutorial

git.md
This PR is more of an issue:
In `git version 2.6.2.windows.1`
`git config --list --show-origin` says
`error: unknown option 'show-origin'`
But just `git config --list` does its job.
If there is any special purpose of using `--show-origin`, and if this is supported only in newer versions of git, then I'd suggest adding instructions for **updating git**.
=> --show-origin option not working for me, perhaps not needed?

python.md
- Labeled as only for advanced people.  The instructions could be
changed to use them more, after they have been tested.
- Linking mainly so that they aren't forgotten.
- To review: will this be too confusing at this stage?
=> python: Link coderefinery/software conda/requirements files

difftools.md
During the Installation help Zoom session, a question came up how to configure Git to use Meld on windows. The problem is that Meld is not added to the path, so Git needs to be told the full path to the executable.
=> Add more explicit Windows Meld installation instructions

git.md
- Closes: #131
- This uses the name "example" to match the video, though I would have
picked something different if I did it again now.
- Review: General check
=> git: verification, don't git init in home dir

content/conda-environment.md
Added instruction to activate `conda` first before activating `coderefinery` environment. In Mac OS X Catalina, when opening a new terminal shell, it was necessary to do this first even though .bash_profile has `export PATH="/Users/naoetatara/miniconda3/bin:$PATH"`. Once it is done, even after deactivating base, as long as the same window opens it is possible to start from "source activate coderefinery" or "conda activate coderefinery"
=> added clarification before activating coderefinery env; closes #164

content/difftools.md
As discussed [here](https://gitlab.gnome.org/GNOME/meld/-/issues/559), Meld 3.20.3 switched to local installation as default. This changed the default install location and also led to some errors where the installer tries to write to the Registry but without elevated privileges. The developers indicate that they might revert to system-wide install in later versions which means that this version might be the only one to have this bug. NB. Future versions will have a (non-default) option to do user only installs that might be suggested in the instructions.
=> Install notes for Meld 3.20.3 on Win, fixes #187

content/shell-and-git.md
- We were debating this in the install time
- We thought the separate steps of `nano` from command line, and
`commit` without `-m` were good because it verifies the editor in
two different ways.
- Also re-state how to exit nano (can't hurt) and provide an example
of a commit message.
- Review:
- Other options considered were `git commit --allow-empty` (no
editor being checked), `git commit -m`, or `git commit
example.txt` without `git add example.txt` (different than we do
in git-intro).
=> content/shell-and-git: Remove `example.txt` from git commit

content/docker.md, content/index.rst, content/make.md
docker instructions greatly shortened to only point to official instructions rather than replicating the steps found there.
both `make` and `docker` instructions put under Optional section
=> revive installation instructions for docker and make, fixes #196

content/shell-and-git.md
This was not clear for a user yesterday. I guess the reference to  Windows "cmd" was the source of the confusion. I added a short sentence on how to start Git Bash.
=> Explicitly mention how to start git bash on Windows

content/conda-environment.md
- No longer needed after current testing.
=> content/conda-environment: Remove special Mac M1 environment

content/index.rst
- The keypoints is a difficult to see green color, change to the
default admonition block type.
- Review: automerge
=> content/index: `keypoints` → `admonition`

content/conda-environment.md
- I might link straight to this page and the back-link is useful.
=> content/conda-environment: Link to the conda page as a prerequisite

content/github.md
One more step that can fail and discourage from installing the rest.
=> do not require github 2FA

content/index.rst, content/shell-and-git.md
- Minor things I saw, should have no semantic effect
- Review: check that Github account really is only needed on day 3 (I
know there is a preview on earlier days, but in effect that can be
skipped / is optional)
=> minor updates: github on day3, link nano part

content/shell-and-git.md
- This says that git<2.28 isn't an emergency and to go on and the
lesson will explain what to do.  I think we decide if this is the
right thing to do or not before merging.  (at least it should say
windows: upgrade, mac: upgrade, linux: go on and deal ?)
=> content/shell-and-git: Check for git>=2.28

content/shell-and-git.md
- This is also done in lessons, but this provides an extra check to
avoid problems.
- Text checked from a video that's a year old.  The rest seems to
match so hopefully the text is correct.
=> content/shell-and-git: Set `main` as default branch in installer

content/index.rst
- Warning to not start installing yet.
- Initial draft of separating weeks
- Mainly separates the weeks in the TOC
- ... but also separates instructions by what method of attendance
they are needed for (web, cli, vscode)
- This is not a very usable yet, but gives us something to think about.
=> content/index: Separate weeks better (initial)

content/editors.md, content/git-in-terminal.md, content/index.md, content/ssh.md, content/vscode.md
- git for windows is still needed (presumably the same for other
operating systems, but it's there automatically)
- Notes about how to do set the editor, for the cases it's needed (I
don't think it's automatically done by vscode?)
- Add VSCode to the SSH/HTTPS page that basically says "nothing is
needed" - they shouldn't be looking here but this will clarify.
(I'm not entirely sure how it works but people seem to find it
does...)
- In Git for Windows instructions, further clarifications about the
setting the editor: emphasize setting VSCode here.
- I think this probably works but is worth someone else taking a look
=> Updates to the vscode track
