coderefinery/installation

- _linux/03-python.md
extended the instructions, added package installation instructions, and included about jupyter. More extensive verifying instructions also
> extend python instructions and add about packages

- _win/03-python.md
Copied text from Linux and OSX instructions  but tried to change to Windows terminology (I'm very inexperienced with windows). Removed virtualenv and pip instructions
> add windows-python first instructions, needs more work

- _linux/09-devops.md
- _osx/09-devops.md
- _win/09-devops.md
Kept these instructions simple. They can be hard for a user, but every
user is not expected to do these installations. The excercises will be
demonstrated.
> Installation instructions for Vagrant

- _linux/03-python.md
- _win/03-python.md
added conda environments, RISE package, and made ipyparallel optional (since it's a bit tricky to set up)
> update python installation instructions

- _linux/03-python.md
moved optional packages to separate heading, and added instructions for installing R, matlab/octave and julia. Also removed ipyparallel since too much material already and it's tricky to set up
> restructuring and adding optional packages

- _linux/02-git.md
- _linux/04-compilers.md
- _linux/05-make.md
- _linux/06-cmake.md
- _linux/07-difftools.md
Fedora switched to dandified yum (dnf) since Fedora 22
> Change yum to dnf

- _osx/06-cmake.md
As discussed in the lesson, I dared to do a pull request on how to configure CMake to run it from the command line in Mac.
> Added How to install CMake for command line use in 06-cmake.md

- docker.md
- index.md
I have added instructions to install docker on different operating systems.
> added docker installation instructions

- python.md
changed the recommendation to python 3.5 or 3.6, and added paragraph about py3 environments within anaconda2 distributions
> recommend py3 and mention conda env for py3

- troubleshooting.md
I am not sure about this (path is different on my Azure) but I think the 3 is better?
> adjust path to anaconda 3

- python.md
i want to move over to teaching JupyterLab in Kiruna, which requires some additional packages and configuration steps
> additional python packages and configs for jupyterlab

- index.md
there is no need to create these explicitly
> travis and coveralls: we sign in using github

- difftools.md
- docker.md
- git.md
- make.md
- python.md
- troubleshooting.md
> Less repetition, make verification harder to miss

- index.md
Since coveralls is not part of testing exercise anymore.
Please merge this after https://github.com/coderefinery/testing/pull/27 is merged.
> we do not need coveralls removal instructions

- git.md
- Do we normally recommend if someone doesn't know that they want
something else?
> Make nano default editor

- snakemake.md
- Thanks to @annefou for the hint that solved it.
- I don't know how WSL vs native anaconda affects things, etc.  Or if
this is even the right answer... please discuss.
> Snakemake on Windows requires snakemake-minimal

- index.md
- zoom.md
- So that they don't have to wait for an email to do it
- to review: this is copied from a template email, but is there
anything else that needs to be said here?
> Add zoom instructions

- git.md
I will add some video icons in a follow-up PR.
> More work on Git configuration

- zoom.md
- We go over them in the workshop itself, but I guess it can't hurt to
make people think about it early.
> Add link to zoom signals

- zoom.md
- Fix zoom link
- Note that zoom can be verified by testing it with other events.
> zoom: fix download link and update verification

- jupyter.md
- Please make sure that this actually is correct and makes sense.
- related to coderefinery/jupyter#62
> Attempt to clarify jupyterlab extension instllation

- snakemake.md
- https://pypi.org/search/?q=snakemake%2Dminimal
- ERROR: No matching distribution found for snakemake-minimal (from -r requirements.txt (line 13))
> snakemake-minimal doesn't exist in PyPI

- zoom.md
- We can emphasize this trick of two joins, in order to share screens.
I told one person in advance and it was helpful, another person
didn't know.
- Review: do we recommend this?  I think we should, we are blind
without screen shares and waste huge amounts of time.
> zoom: Add note about two zooms, one for chat and one for screenshare

- index.md
- This was in the mega-workshop and a few other workshops, but there
is no reason it shouldn't be moved here.
- To review: not much I think, but we should add other universities
here.
> index: Add link to university-specific instructions

- index.md
> index: update Aalto instructions link

- jupyter.md
- python.md
- Review:
- Fact check (is there any better way to do things?)
- Does this match our general opinion?
> jupyterlab: note that extensions are hard when not using conda

- difftools.md
- Review: general check.  Is this what we want to say?
> difftools: Note that difftools are not a blocker

- python.md
- snakemake.md
- for both windows and linux/mac users
- For windows users add info about anaconda navigator
- only show one way to install Python using anaconda
> simplify python/snakemake install

- index.md
- python-testing.md
this is for software testing hackathons where only pytest is needed
> add new page with python-testing installation

- content/motivation.md
- Mention setup as a lesson
- Mention working with someone as a lesson
- Review
- Does this make it too long without adding enough value?  If so,
reject this PR.
> content/motivation: setup is a lesson, too

- content/github.md
- Don't make it seem like a recommended option, but do say what will
go wrong if you don't use Github to help those who choose that path.
- Review
- Is the increased length worth it?  If not, reject this PR.
- What other major points should we point out?
> content/github: Add section on avoiding Github

- content/conda-environment.md
- content/conda.md
- content/index.rst
- content/license.md
- content/shell-and-git.md
- Review: general check, these are all small unsorted changes.
> Misc changes throughout

- content/license.md
- content/shell-and-git.md
- old/git.md
> copy+adapt Carpentries install text into tabs; closes #152

- content/conda-environment.md
- content/conda.md
- content/index.rst
I tried making the checklist look more important to make sure that everyone goes through it. 
https://user-images.githubusercontent.com/56588774/116611316-88009600-a936-11eb-8255-b358bbda2295.mov
Also, I changed "Miniconda or Anaconda" to emphasize recommendation of Miniconda rather than Anaconda.
I would like to implement reason why CR recommends Anaconda rather than Miniconda (ref. [Zulip "installation instructions" thread in lessons stream](https://coderefinery.zulipchat.com/#narrow/stream/136238-lessons/topic/installation.20instructions/near/236735174), so I keep this as draft pull request.
> Clarification of necessary steps by page design and Miniconda recommendation

- content/github.md
- content/index.rst
- content/shell-and-git.md
- content/ssh.md
> Clarify more about Github+SSH

- content/ssh.md
- Make it clear where the actual instructions are, before it was hid
in the third paragraph.
- Clarify the point of ssh related to git in the first paragraph.
- Review: general check
> content/ssh: Clarify where the instructions are

- content/ssh.md
> content/ssh: Note that other error messages do not matter.

- content/ssh.md
A tiny change for clearer instructions.
> (language) Minor update

- content/zoom.md
- Better explain different types of workshops
- Other miscellaneous updates
- There are still some ambiguities, for example do you need to rename
yourself to team names if it is a livestearm workshop (in manuals,
not here).  I think it is better to ignore this rather than make the
instructions fully general, details can be said on workshop page.
- Review: general check
> content/zoom: Add note at top about types of workshops, misc reorganization

- content/conda.md
based on discussion at install session today
> note about anaconda vs miniconda

- content/conda-environment.md
- content/conda.md
- content/difftools.md
- content/docker.md
- content/editors.md
- content/make.md
- content/shell-and-git.md
- Needs follow-up PR to use the new version of sphinx-copybutton for
optimal user experience (but in most cases the `$` would have been
copied anyway).
- Review: automerge
> Adjust highlight language, `bash` -> `console`

- content/editors.md
- Nano is what we recommend most if you don't know what to do, so make
it more clear than the others.
- Make it clear that it usually doesn't need special installation.
This came up in an install help session.
- Review: this should be fact-checked for each operating system, I am
not entirely sure about any of them but I think this is the
situation...
> content/editors: Add note about nano installation

- content/index.rst
- Since it has to be done after step 2 anyway.
- Review: general check, minimal changes to content.
> content/index: Move verification script to bottom

- content/github.md
- As discussed in chat
- Closes: #246
- Review: automerge
> content/github: MFA note

- content/shell-and-git.md
From issues, seeing someone do it, and verifying with a video
recording found online.
- Closes: #253
- Closes: #259
- Closes: #254
- Also mention possibilities of setting the editor, since it seems to do the right thing.
- #252 lists what a setup with these options sets as config settings
> content/shell-and-git: Updates based on latest installer

- content/shell-and-git.md
- This isn't tested so read carefully, but it probably works.
- Closes: #256
> content/shell-and-git: mac: add note to check if git already installed

- content/conda.md
- Related to #258 but I'm not quiet sure if it closes it.
> content/conda: note to restart terminal to take conf into effect

- content/index.rst
- While this isn't a requirement, is this the best way to make sure
that people see it?
- Feel free to not merge
> content/index: Add cheatsheet to requirements table

- content/shell-and-git.md
I have added one troubleshooting solution for Windows laptop managed by organisations. This has happened in the past with both Aalto University and University of Helsinki Windows laptops.
> Windows laptops managed by organisations

- content/shell-and-git.md
I have added a sentence to raise awareness that different organisations have different policies regarding automatic backups, and changing the HOME to point to the local physical disk might result in no backups.
> windows managed by organisations

- content/ssh.md
- verify/verify-installation.sh
- This is based on my best knowledge but I haven't fully tested.
- I have tested on Windows.
- Review
- Do we want to offer both options?
- What are the risks?
> content/ssh: Add "git credential manager" to the SSH page.

- content/index.md
Goal is to make it more generic if part 2 is done over multiple days
> Replacing "weeks" with "parts"
